configfile: "../config.yaml"

subworkflow orf:
    workdir: "../orf"

subworkflow ccle:
    workdir: "../ccle"

subworkflow tcga:
    workdir: "../tcga"

import glob
manual = [ x[:-5] for x in glob.glob("../candidates/*.yaml") ]
dsets = [ x.replace("dset_", "").replace(".r", "") for x in glob.glob("dset_*.r") ]

# H3F3C: excluded because pseudogene in new run
bygene = [ "CDKN1A", "SNRPA", "RBM12", "RBM14", "SNRPA", "HES1", "HNRNPL", # all 3
           "DAZAP1", "BANP", "PKNOX1", "PTBP1", "SFPQ", "ATXN1",
           "DHX9", "FUBP1", "FUS", "GTF2H2C", #"H3F3C", # cutoff
           "HNRNPM", "HSP90AB2P", "ITGA10", "KHDRBS1", "LRRC37A2", "MNT",
           "NSF", "PA2G4P4", "PPP1R10", "PRDM10", "RPL23AP7", "FAM86FP",
           "RPS9", "RREB1", "SAFB", "TRA2B", "SELP", "CHD4", "RPL23P8",
           "TRANK1", "UBC", "UBTF", "ZFR", "ZHX2", "ZNF143", "ZBTB14", # not in orf
           "OVOL2", "KLF5" ] # lm3 addition

rule all:
    input:
        expand("{gene}/{dset}.pdf", gene=bygene, dset=dsets)

rule by_gene:
    input:
        rscript = "by_gene.r"
    output:
        outfile = "by_gene/{gene}.rds"
    resources:
        mem = 10240
    shell:
        "Rscript {input.rscript}"
            " --config ../config.yaml"
            " --gene {wildcards.gene}"
            " --outfile {output.outfile}"

rule dset:
    input:
        rscript = "dset_{dset}.r",
        infile = "by_gene/{gene}.rds"
    output:
        plotfile = "{gene}/{dset}.pdf"
    resources:
        mem = 15360
    shell:
        "Rscript {input.rscript}"
            " --gene {wildcards.gene}"
            " --infile {input.infile}"
            " --plotfile {output.plotfile}"
