genesets:
    - GO_Biological_Process_2020
    - GO_Biological_Process_2021
    - GO_Cellular_Component_2021
    - DoRothEA
    - ChEA_2016
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - miRTarBase_2017
    - MSigDB_Oncogenic_Signatures
    - MSigDB_Hallmark_2020
    - CORUM_core
    - CORUM_all
    - CORUM_splice
    - HMDB_Metabolites
    - InterPro_Domains_2019
    - manual
    - CIN
    - DDR

orf_tissues:
    - pan
    - NB
    - OV
    - BRCA
    - SKCM
    - MB
    - LUAD # only H2077
    - PRAD # only LNCaP

ccle_tissues:
    - pan
    - BRCA
    - LUAD
    - LUSC
    - NSCLC
    - SCLC
    - SKCM
    - COADREAD
    - OV
    - PRAD

tcga_tissues:
    - pan
    - BRCA
    - LUAD
    - LUSC
    - NSCLC
    - HNSC
    - KIRC
    - SKCM
    - COADREAD
    - OV
    - PRAD

cor_tissues:
    - pan
#    - BRCA
#    - OV
#    - SKCM
#    - LUAD
#    - LUSC
#    - NSCLC
#    - PRAD
#    - COADREAD

tcga_adj:
    - naive
    - pur
    - puradj

euploid_tol: 0.15
