genesets:
    - GO_Biological_Process_2020
    - DoRothEA
    - ChEA_2016
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - miRTarBase_2017
    - MSigDB_Oncogenic_Signatures
    - MSigDB_Hallmark_2020
    - CORUM
    - HMDB_Metabolites
    - manual

orf_tissues:
    - pan
    - NB
    - OV
    - BRCA
    - SKCM
    - MB
    - LUAD # only H2077
    - PRAD # only LNCaP

ccle_tissues:
    - pan
    - BRCA
    - LUAD
    - LUSC
    - SCLC
    - SKCM
    - COADREAD
    - OV
    - PRAD

tcga_tissues:
    - pan
    - BRCA
    - LUAD
    - LUSC
    - HNSC
    - KIRC
    - SKCM
    - COAD
    - OV
    - PRAD

cor_tissues:
    - pan
    - BRCA
    - OV
    - SKCM
    - LUAD
    - LUSC
    - PRAD

# all the fits that should be calculated
fits:
#    - rlm
#    - rlm2
    - rlm3
    - lm3
#    - lm3r

# which fits are plotted in top hit comparisons
fit_compare:
#    - rlm2
    - rlm3
    - lm3
#    - lm3r


tcga_adj:
    - naive
    - pur
#    - puradj # only required for rlm<3

euploid_tol: 0.15
