genesets:
    - GO_Biological_Process_2018
    - ChEA_2016
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - miRTarBase_2017
    - MSigDB_Oncogenic_Signatures
    - CH.HALLMARK
    - CORUM

orf_tissues:
    - pan
    - NB
    - OV
    - BRCA
    - SKCM
    - MB
    - LUAD # only H2077
    - PRAD # only LNCaP
