genesets:
    - GO_Biological_Process_2018
    - ChEA_2016
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - miRTarBase_2017
    - MSigDB_Oncogenic_Signatures
    - CH.HALLMARK
    - CORUM
    - manual

orf_tissues:
    - pan
    - NB
    - OV
    - BRCA
    - SKCM
    - MB
    - LUAD # only H2077
    - PRAD # only LNCaP

ccle_tissues:
    - pan
    - BRCA
    - LUAD
    - SCLC
    - SKCM
    - COADREAD
    - OV
    - PRAD

tcga_tissues:
    - pan
    - BRCA
    - LUAD
    - LUSC
    - HNSC
    - KIRC
    - SKCM
    - COAD
    - OV
    - PRAD

cor_tissues:
    - pan
    - BRCA
    - OV
    - SKCM
    - LUAD
    - PRAD

euploid_tol: 0.15
