configfile: "../config.yaml"

subworkflow genesets:
    workdir: "../data/genesets"

subworkflow orf:
    workdir: "../orf"

subworkflow tcga:
    workdir: "../tcga"

mem = { 'pan' : 30720, '*' : 5120 }
cores = { 'pan' : 5, '*' : 5 }
time = { 'pan' : 720, '*' : 360 }

tissues = config['tcga_tissues']
fits = ['gene']#, 'cpg']
sets = set(config['genesets']) - set('genes')

rule all:
    input:
        expand("{tissue}/{fit}.pdf", tissue=tissues, fit=fits),
#        expand("{tissue}/cor-comp.pdf", tissue=tissues, fit=fits),
        expand("{tissue}/cor-comp.pdf", tissue=['pan'], fit=fits), # no stan-nb avail for tissues
        expand("{tissue}/{fit}/{gset}.pdf",
                tissue=tissues, gset=config['genesets'], fit=fits)

rule fit:
    input:
        rscript = "fit_{fit}.r"
    output:
        outfile = "{tissue}/{fit}.xlsx",
        plotfile = "{tissue}/{fit}.pdf"
    resources:
        mem = lambda wc: [ mem[wc.tissue] if wc.tissue in mem.keys() else mem['*'] ][0],
        cores = lambda wc: [ cores[wc.tissue] if wc.tissue in cores.keys() else cores['*'] ][0],
        walltime = lambda wc: [ time[wc.tissue] if wc.tissue in time.keys() else time['*'] ][0]
    wildcard_constraints:
        fit = "(?!cor-comp).*"
    shell:
        "Rscript {input.rscript}"
            " --tissue {wildcards.tissue}"
            " --cores {resources.cores}"
            " --memory {resources.mem}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule gset:
    input:
        rscript = "../ccle_meth/gset.r",
        infile = "{tissue}/{fit}.xlsx",
        setfile = genesets("{gset}.rds")
    output:
        plotfile = "{tissue}/{fit}/{gset}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --setfile {input.setfile}"
            " --plotfile {output.plotfile}"

rule cor:
    input:
        rscript = "cor-comp.r",
        comp_naive = tcga("{tissue}/stan-nb_naive.rds"),
        comp_pur = tcga("{tissue}/stan-nb_pur.rds"),
#        comp_puradj = tcga("{tissue}/stan-nb_puradj.rds"),
        orf = orf("{tissue}/genes.xlsx"),
        meth = "{tissue}/gene.xlsx"
    output:
        plotfile = "{tissue}/cor-comp.pdf"
    shell:
        "Rscript {input.rscript}"
            " --tissue {wildcards.tissue}"
            " --comp_naive {input.comp_naive}"
            " --comp_pur {input.comp_pur}"
#            " --comp_puradj {input.comp_puradj}"
            " --orf {input.orf}"
            " --meth {input.meth}"
            " --plotfile {output.plotfile}"
