ccle = {
    'annot' : 'Cell_lines_annotations_20181226.txt',
    'rnaseq' : 'CCLE_RNAseq_genes_counts_20180929.gct.gz',
    'copies' : 'CCLE_copynumber_byGene_2013-12-03.txt.gz'
}

arrayexpress = {
    'gdsc' : 'E-MTAB-3983/static/E-MTAB-3983-atlasExperimentSummary.Rdata',
    'ccle' : 'E-MTAB-2770/static/E-MTAB-2770-atlasExperimentSummary.Rdata'
}

depmap = {
    'mut' : 'CCLE_mutations.csv',
    'meth' : 'CCLE_RRBS_TSS_1kb_20180614.txt'
}

rule all:
    input:
        "dset.rds"

rule ccle_download:
    output:
        outfile = "{file}"
    shell:
        "wget -N https://data.broadinstitute.org/ccle/{file}"

#rule depmap_meth:
#    output:
#        outfile = "{file}"
#    shell:
#        "wget -N https://depmap.org/portal/download/api/download/external?file_name={file}"

rule dset:
    input:
        rscript = "dset.r",
        annot = ccle['annot'],
        rnaseq = ccle['rnaseq'],
        copies = ccle['copies'],
        mut = depmap['mut'],
        meth = depmap['meth']
    output:
        outfile = "dset.rds"
    resources:
        mem = 4096,
    shell:
        "Rscript {input.rscript}"
            " --annot {input.annot}"
            " --rnaseq {input.rnaseq}"
            " --copies {input.copies}"
            " --mut {input.mut}"
            " --meth {input.meth}"
