configfile: "../config.yaml"

subworkflow orf:
    workdir: "../orf"
    snakefile: "../orf/Snakefile"

subworkflow ccle:
    workdir: "../ccle"
    snakefile: "../ccle/Snakefile"

subworkflow tcga:
    workdir: "../tcga"
    snakefile: "../tcga/Snakefile"

rule all:
    input:
        expand("{tissue}_{fit}_{cna}/{sets}.pdf",
                fit = ['rlm', 'rank'],
                sets = config['genesets'] + ['genes'],
                tissue = ['pan', 'BRCA', 'SKCM', 'OV', 'LUAD', 'PRAD'],
                cna = ['amp']) # del, all

rule cor:
    input:
        rscript = "cor.r",
        orf = orf("{tissue}/{sets}.xlsx"),
        ccle = ccle("{tissue}_{fit}/{sets}.xlsx"),
        tcga_naive = tcga("naive/{tissue}_{fit}/{sets}.xlsx"),
        tcga_pur = tcga("pur/{tissue}_{fit}/{sets}.xlsx"),
        tcga_puradj = tcga("puradj/{tissue}_{fit}/{sets}.xlsx")
    output:
        plotfile = "{tissue}_{fit}_{cna}/{sets}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --orf {input.orf}"
            " --ccle {input.ccle}"
            " --tcga_naive {input.tcga_naive}"
            " --tcga_pur {input.tcga_pur}"
            " --tcga_puradj {input.tcga_puradj}"
            " --sets {wildcards.sets}"
            " --cna {wildcards.cna}"
            " --plotfile {output.plotfile}"
