configfile: "../config.yaml"

subworkflow data:
    workdir: "../data"

subworkflow genesets:
    workdir: "../data/genesets"

from collections import defaultdict as dd
mem = dd(lambda: 1536, { 'pan' : 2048 })
cores = dd(lambda: 70, { 'pan' : 70 })
time = dd(lambda: 6*60, { 'pan' : 12*24*60 })

rule all:
    input:
        expand("fit_{tcga_adj}/{tcga_tissues}.pdf", **config),
        expand("fit_{tcga_adj}/{tcga_tissues}/{genesets}.pdf", **config),
        expand("bionet/{tcga_tissues}.pdf", **config)

rule fits:
    input:
        expand("fits_{tcga_adj}/{tcga_tissues}.rds", **config)

rule fit:
    input:
        rscript = "fit_brms.r",
        infile = data("df_tcga.rds")
    output:
        outfile = "fit_{type}/{tissue}.rds"
    resources:
        mem = lambda wc: mem[wc.tissue],
        cores = lambda wc: cores[wc.tissue],
        walltime = lambda wc: time[wc.tissue]
    group: "fit_and_plot"
    wildcard_constraints:
        fit = "[a-z0-9-]+"
    shell:
        "nice -n 10 Rscript {input.rscript}"
            " --tissue {wildcards.tissue}"
            " --type {wildcards.type}"
            " --cores {resources.cores}"
            " --memory {resources.mem}"
            " --outfile {output.outfile}"

rule plot:
    input:
        rscript = "../ccle/plot.r",
        infile = "{fit}_{type}/{tissue}.rds"
    output:
        plotfile = "plot_{type}/{tissue}.pdf"
    group: "fit_and_plot"
    wildcard_constraints:
        type = "[a-z]+",
        fit = "[a-z0-9-]+",
        tissue = "[a-zA-Z0-9]+"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --plotfile {output.plotfile}"

rule gset:
    input:
        rscript = "../ccle/gset.r",
        infile = "fit_{type}/{tissue}.rds",
        setfile = genesets("{gset}.rds"),
    output:
        outfile = "plot_{type}/{tissue}/{gset}.rds",
        plotfile = "plot_{type}/{tissue}/{gset}.pdf"
    wildcard_constraints:
        fit = "[a-z0-9-]+",
        type = "[a-z0-9-]+"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --setfile {input.setfile}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule bionet:
    input:
        rscript = "../ccle/bionet.r",
        infile = "fit_puradj/{tissue}.rds"
    output:
        plotfile = "bionet/{tissue}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --n_genes 500"
            " --plotfile {output.plotfile}"
