tissues = ["pan", "BRCA", "LUAD", "LUSC", "HNSC", "KIRC", "SKCM", "COAD", "OV"]

types = ['naive', 'pur', 'pur+adj']

mem = {
    "pan" : 61440,
    "*" : 4096
}

rule all:
    input:
        expand("{type}/{tissue}.{ext}", tissue=tissues, ext=['pdf','xlsx'], type=types)

rule do_fit:
    input:
        rscript = "tcga_{type}.r"
    output:
        outfile = "{type}/{tissue}.xlsx",
        plotfile = "{type}/{tissue}.pdf"
    resources:
        mem = lambda wc: mem[wc.tissue] if wc.tissue in mem.keys() else mem["*"],
        walltime = 120
    shell:
        "Rscript {input.rscript}"
            " --tissue {wildcards.tissue}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
