comps = ['rbm8_vs_luc8', 'rbm24_vs_luc24', 'rbm72_vs_luc72']

rule all:
    input:
        expand("rmats_out/{comp}", comp=comps),
        expand("splice_{comp}.pdf", comp=comps)

rule rmats:
    input:
        sample1 = "{sample1}.txt",
        sample2 = "{sample2}.txt"
    output:
        tmpdir = directory("rmats_tmp/{sample1}_vs_{sample2}"),
        outdir = directory("rmats_out/{sample1}_vs_{sample2}")
    shell:
        "python ~/rmats-turbo/rmats.py"
            " --b1 {input.sample1}"
            " --b2 {input.sample2}"
            " --gtf ../H838_RBM14/genes_with_ERCC.gtf"
            " --readLength 150"
            " --allow-clipping"
            " --nthread 12"
            " --od rmats_out/{wildcards.sample1}_vs_{wildcards.sample2}"
            " --tmp rmats_tmp/{wildcards.sample1}_vs_{wildcards.sample2}"
        #-t paired \

rule eset:
    input:
        rscript = "eset.r",
        infile = "STAR_Gene_Counts.csv"
    output:
        outfile = "eset.rds",
        plotfile = "eset.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule diff_expr:
    input:
        rscript = "diff_expr.r",
        eset = "eset.rds"
    output:
        outfile = "diff_expr.rds",
        plotfile = "diff_expr.pdf"
    shell:
        "Rscript {input.rscript}"
            " --eset {input.eset}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule splice:
    input:
        rscript = "splice.r"
    output:
        plotfile = "splice_{comp}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --comp {wildcards.comp}"
            " --plotfile {output.plotfile}"
