subworkflow ccle:
    workdir: "ccle"

rule all:
    input:
        "df_ccle.rds",
        "df_tcga.rds",
        "de_tcga.rds"

rule ccle:
    input:
        rscript = "df_ccle.r",
        infile = ccle("dset.rds")
    output:
        outfile = "df_ccle.rds"
    resources:
        mem = 4096
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --outfile {output.outfile}"

rule tcga:
    input:
        rscript = "df_tcga.r"
    output:
        outfile = "df_tcga.rds"
    resources:
        mem = 120 * 1024,
        walltime = 120
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.outfile}"

rule de_tcga:
    input:
        rscript = "de_tcga.r"
    output:
        outfile = "de_tcga.rds"
    resources:
        mem = 30 * 1024,
        walltime = 120
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.outfile}"

rule gistic:
    input:
        rscript = "tcga_prod2-gistic.r"
    output:
        outfile = "tcga_prod2-gistic.rds"
    shell:
        "Rscript {input.rscript}"

rule gistic_smooth:
    input:
        rscript = "gistic_smooth.rds"
        infile = "tcga_prod2-gistic.rds"
    output:
        outfile = "gistic_smooth.rds"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --outfile {output.outfile}"
