subworkflow data_ccle:
    workdir: "../data/ccle"
    snakefile: "../data/ccle/Snakefile"

subworkflow genesets:
    workdir: "../data/genesets"
    snakefile: "../data/genesets/Snakefile"

tissues = ["pan", "BRCA", "LUAD", "SCLC", "SKCM", "COADREAD", "OV"]
#tissues = ["pan", "BRCA", "LUAD", "SKCM", "COADREAD", "ALL", "DLBC",
#           "BLCA", "KIRC", "HNSC", "LUSC", "LIHC", "OV", "PAAD",
#           "STAD", "UCEC", "GBM", "ESCA"]

rule all:
    input:
        expand("{tissue}.{ext}", tissue=tissues, ext=['pdf','xlsx'])

rule fit_gene:
    input:
        rscript = "fit_gene.r",
        infile = data_ccle("dset.rds")
    output:
        outfile = "{tissue}/genes.xlsx",
        plotfile = "{tissue}/genes.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --tissue {wildcards.tissue}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule fit_set:
    input:
        rscript = "fit_set.r",
        infile = data_ccle("dset.rds"),
        setfile = genesets("{set}.rds")
    output:
        outfile = "{tissue}/{set}.xlsx",
        plotfile = "{tissue}/{set}.pdf"
    wildcard_constraints:
        set = "((?!genes).*)"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --setfile {input.setfile}"
            " --tissue {wildcards.tissue}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
